watchlist/urls.py
from django.urls import path
from .views import HomeView, SearchView, add_movie, MovieDetailView, MovieDelete, set_watched, watchlist

app_name = 'watchlist'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('search/add/', add_movie, name='add'),
    path('watchlist/', watchlist, name='watchlist'),
    path('movie/<int:pk>/', MovieDetailView.as_view(), name='movie'),
    path('delete/<int:pk>/', MovieDelete.as_view(), name='delete'),
    path('watched/<int:pk>/', set_watched, name='set_watched'),
]

yomdb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('watchlist.urls', namespace='watchlist'))
]

watchlist/models.py
from django.db import models


class Actor(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Movie(models.Model):
    imdbID = models.CharField(max_length=50)
    title = models.CharField(max_length=200)
    watched = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)
    actors = models.ManyToManyField(Actor)
    genres = models.ManyToManyField(Genre)

    def __str__(self):
        return self.title

watchlist/forms.py
from django.forms import ModelForm

watchlist/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View, DetailView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from .models import Movie, Actor, Genre
import json
import requests


class HomeView(View):
    def get(self, *args, **kwargs):
        return render(self.request, "home.html")


class SearchView(View):
    def get(self, *args, **kwargs):
        return render(self.request, "search.html")


def is_valid_param(param):
    return param != '' and param is not None


def filter(request):
    qs = Movie.objects.all()
    title_or_actor_query = request.GET.get('title_or_actor')
    genre = request.GET.get('genre')
    watched = request.GET.get('watched')
    not_watched = request.GET.get('not_watched')

    if is_valid_param(title_or_actor_query):
        qs = qs.filter(Q(title__icontains=title_or_actor_query) | Q(actors__name__icontains=title_or_actor_query)).distinct()
    if is_valid_param(genre) and genre != 'Choose...':
        qs = qs.filter(genres__name=genre)
    if watched == 'on':
        qs = qs.filter(watched=True)
    elif not_watched == 'on':
        qs = qs.filter(watched=False)

    return qs


def watchlist(request):
    qs = filter(request)
    context = {
        'movies': qs,
        'genres': Genre.objects.all()
    }
    return render(request, "watchlist.html", context)


class MovieDetailView(DetailView):
    model = Movie
    template_name = "movie.html"


def add_movie(request):
    imdbID = json.loads(request.body.decode('utf-8')).get('imdbID')
    movies_qs = Movie.objects.filter(imdbID=imdbID)
    if movies_qs.exists():
        return redirect("watchlist:watchlist")
    else:
        api_key = '6f665eb1'
        url = f'http://www.omdbapi.com/?i={imdbID}&apikey={api_key}'
        response = requests.get(url)
        vals = json.loads(response.text)

        movie = Movie.objects.create(
            imdbID=vals.get('imdbID'),
            title=vals.get('Title'),
        )
        actors = vals.get('Actors').split(',')
        for name in actors:
            actor, created = Actor.objects.get_or_create(name=name)
            movie.actors.add(actor)

        genres = vals.get('Genre').split(',')
        for name in genres:
            genre, created = Genre.objects.get_or_create(name=name)
            movie.genres.add(genre)

        return redirect("watchlist:watchlist")


class MovieDelete(DeleteView):
    model = Movie
    success_url = reverse_lazy("watchlist:watchlist")


def set_watched(request, pk):
    movie = get_object_or_404(Movie, id=pk)
    movie.watched = False if movie.watched else True
    movie.save()
    return redirect("watchlist:watchlist")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Home</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="{% url 'watchlist:home' %}">YOMDB</a><button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'watchlist:search' %}">Search Movies</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'watchlist:watchlist' %}">Watchlist</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content  %}
        {% endblock content %}


        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Uglaos</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- Axios script -->
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

<section class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <div class="col-lg-10 align-self-end">
                <h1 class="text-uppercase text-white font-weight-bold">Your Own Movie Database</h1>
                <hr class="divider my-4"/>
            </div>
            <div class="col-lg-8 align-self-baseline">
                <p class="text-white-75 font-weight-light mb-5">Gives you and your colleagues, friends a new
                    experience in watching and sharing movies.</p>
                <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'watchlist:watchlist' %}">Watchlist</a>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/movie.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<section class="masthead search-masthead">

    <div class="container">
        <div class="row align-items-center justify-content-center text-center">
            <div class="table-responsive text-nowrap mt-5 mb-5">
                <h3 class="text-uppercase text-white font-weight-bold mt-5 mb-2">{{ object.title }}</h3>
                {% for genre in object.genres.all %}
                <p class="btn btn-primary btn-sm">{{ genre.name }} </p>
                {% endfor %}
                <hr>
                <h4 class="text-white font-weight-bold mb-4">Actors</h4>
                {% for actor in object.actors.all %}
                <p class="text-white">{{ actor.name }} </p>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/search.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<section class="masthead search-masthead">
    <div class="container">
        <div class="row align-items-center justify-content-center text-center mt-5">
            <div class="col-lg-10 align-self-end">
                <h3 class="text-uppercase text-white font-weight-bold">Movie Search</h3>
                <hr class="divider my-4"/>
            </div>
            <div class="col-lg-8 align-self-baseline">
                <form id="movieSearchForm">
                    <input type="text" class="form-control" id="searchText" placeholder="Search Movies...">
                </form>
            </div>

            <div class="mt-5 mb-5">
                <div id="movies" class="row">

                </div>
            </div>

        </div>


    </div>

</section>

{% endblock content %}

templates/watchlist.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<section class="masthead search-masthead">

    <div class="container">
        <div class="row align-items-center justify-content-center text-center">
            <div class="table text-nowrap mt-5 mb-5">
                <h3 class="text-uppercase text-white font-weight-bold">Watchlist</h3>
                <form method="GET" action=".">
                    <div class="form-row pt-3">
                        <div class="form-group col-12">
                            <div class="input-group">
                                <input class="form-control py-2 border-right-0 border" type="search"
                                       name="title_or_actor" placeholder="Title or actor..."/>
                                <span class="input-group-append">
                                    <div class="input-group-text bg-transparent">
                                        <i class="fa fa-search"></i>
                                    </div>
                                </span>
                                <select id="genre" class="form-control ml-3" name="genre">
                                    <option selected>Choose...</option>
                                    {% for genre in genres %}
                                    <option value="{{ genre }}">{{ genre }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="watched" name="watched">
                            <label class="form-check-label text-white" for="watched">Watched</label>
                            <input class="form-check-input ml-4" type="checkbox" id="not_watched" name="not_watched">
                            <label class="form-check-label text-white ml-5" for="not_watched">Not watched</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
                <table class="table mt-5">
                    <thead>
                    <tr>
                        <th scope="col" class="movie-name">#</th>
                        <th scope="col" class="movie-name">Title</th>
                        <th scope="col" class="movie-name">Date Added</th>
                        <th scope="col" class="movie-name">Watched</th>
                        <th scope="col" class="movie-name">Remove</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for movie in movies %}
                    <tr>
                        <td scope="row" class="movie-name">{{ forloop.counter }}</td>
                        <td class="text-white font-weight-bold"><a href="/movie/{{ movie.id }}/">{{ movie.title }}</a></td>
                        <td scope="row" class="movie-name">{{ movie.date_added }}</td>
                        <td class="movie-name">
                            {% if movie.watched %}
                            <a href="{% url 'watchlist:set_watched' movie.id %}">
                                <svg class="bi bi-check-square-fill" width="1em" height="1em" viewBox="0 0 16 16"
                                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                          d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                </svg>
                            </a>
                            {% else %}
                            <a href="{% url 'watchlist:set_watched' movie.id %}">
                                <svg class="bi bi-x-square-fill" width="1em" height="1em" viewBox="0 0 16 16"
                                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                          d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm9.854 4.854a.5.5 0 0 0-.708-.708L8 7.293 4.854 4.146a.5.5 0 1 0-.708.708L7.293 8l-3.147 3.146a.5.5 0 0 0 .708.708L8 8.707l3.146 3.147a.5.5 0 0 0 .708-.708L8.707 8l3.147-3.146z"/>
                                </svg>
                            </a>
                            {% endif %}
                        </td>
                        <td>
                            <form action="{% url 'watchlist:delete' movie.id %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="movie_id" value="{{ movie.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm movie-name">
                                    <svg class="bi bi-trash-fill" width="1em" height="1em" viewBox="0 0 16 16"
                                         fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd"
                                              d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
                                    </svg>
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3" class="movie-name">There are no movies, please add some to the database...</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            {% endif %}

            <li class="page-item active">
                <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                    <span class="sr-only">(current)</span>
                </a>
            </li>

            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    <!--Pagination-->

</section>


{% endblock content %}